#!/bin/bash

#SBATCH -J build_cache
#SBATCH -N 1
#SBATCH -o build_cache.%j
#SBATCH -p debug
#SBATCH -t 00:30:00

export OMP_NUM_THREADS=1

source /usr/common/contrib/bccp/conda-activate.sh 3.6

(cd ../; python setup.py sdist )
version=`python ../setup.py --version`

bcast-pip ../dist/imaginglss-$version.tar.gz

srun -n 1 python -u ../scripts/imglss-build-cache.py --conf /project/projectdirs/m779/yfeng1/imaginglss/dr3.conf.py



