#!/bin/bash

#SBATCH -J build_cache
#SBATCH -n 512
#SBATCH -o build_cache.%j
#SBATCH -p debug
#SBATCH -t 00:30:00

export OMP_NUM_THREADS=1
module load python/2.7-anaconda

source /project/projectdirs/m779/python-mpi/nersc/activate.sh
mirror ../ imaginglss scripts

# use without installing
export PYTHONPATH=/dev/shm/local:$PYTHONPATH

srun -n 256 python-mpi /dev/shm/local/scripts/imglss-mpi-build-cache.py --conf /project/projectdirs/m779/imaginglss/dr2.conf.py



