#!/bin/bash

#SBATCH -A desi
#SBATCH -J make_rans
#SBATCH -n 512
#SBATCH -o make_rans.%j
#SBATCH -p debug
#SBATCH -t 00:29:00

export OMP_NUM_THREADS=1
set -x

module load python/3.5-anaconda
source /usr/common/contrib/bccp/python-mpi-bcast/nersc/activate.sh

# install the 'nersc' version of imaginglss
bcast-pip bigfile /project/projectdirs/desi/users/yfeng1/imaginglss/imaginglss

time srun -n 512 python-mpi -u /dev/shm/local/bin/imglss-mpi-make-random.py \
    --conf /project/projectdirs/desi/users/yfeng1/imaginglss/legacysurvey/dr3.conf.py \
    20000000 \
    /project/projectdirs/desi/users/yfeng1/imaginglss/legacysurvey/dr3/RANDOM.hdf5
