#!/bin/bash

#SBATCH -J make_random
#SBATCH -n 512
#SBATCH -o make_random.%j
#SBATCH -p debug
#SBATCH -t 00:30:00

export OMP_NUM_THREADS=1
module load python/2.7-anaconda

source /project/projectdirs/m779/python-mpi/nersc/activate.sh

mirror ../ imaginglss scripts

# use without installing
export PYTHONPATH=/dev/shm/local:$PYTHONPATH

srun -n 256 python-mpi /dev/shm/local/scripts/imglss-mpi-make-random.py 6000000 LRG_rand.txt --with-tycho DECAM_LRG --conf /project/projectdirs/m779/imaginglss/dr2.conf.py

#srun -n 256 python-mpi /dev/shm/local/scripts/make_random.py 400000 ELG_rand.txt --with-tycho DECAM_ELG --conf /project/projectdirs/m779/imaginglss/dr2.conf.py

#srun -n 256 python-mpi /dev/shm/local/scripts/make_random.py 6000000 QSO_rand.txt --with-tycho DECAM_QSO --conf /project/projectdirs/m779/imaginglss/dr2.conf.py
