#!/bin/bash
#SBATCH -p shared
#SBATCH -t 00:20:00
#SBATCH -n 6

# This head node script will post process all target types given on the command line
# in parallel, on a head node. e.g.
#
#   bash postprocess.sh FDR_ELG FDR_LRG FDR_QSO
#
#
# Require: RANDOM.hdf5 generated by make_rans.job
# Require: {TARGET}.hdf5 generated by select_objs.job

# http://stackoverflow.com/a/8366378
# kill sub-shells if the script is killed.
trap "kill 0" SIGINT

DIR=`mktemp -d`
pip install --ignore-installed --no-deps --install-option="--prefix=$DIR"  \
      bigfile /project/projectdirs/desi/users/yfeng1/imaginglss/imaginglss
trap "rm -rf $DIR" EXIT


PREFIX=/project/projectdirs/desi/users/yfeng1/imaginglss/legacysurvey/dr3/
OPTIONS=" --conf /project/projectdirs/desi/users/yfeng1/imaginglss/legacysurvey/dr3.conf.py"
#OPTIONS+=" --extra-target-definitions $PWD/../targets"

export PYTHONPATH=$DIR/lib/python3.5/site-packages
export PATH=$DIR/bin:$PATH

mkdir -p $PREFIX

cd $PREFIX

if ! [ -f RANDOM.hdf5 ]; then
    echo "RANDOM.hdf5 not found!"
    exit 1
fi

for T in $*; do
    cp RANDOM.hdf5 $T-RANDOM.hdf5
    (
    python `which imglss-query-tycho-veto.py` $OPTIONS $T-RANDOM.hdf5
    python `which imglss-query-tycho-veto.py` $OPTIONS $T.hdf5
    python `which imglss-query-completeness.py` $OPTIONS --use-tycho-veto=BOSS_DR9 $T $T.hdf5 $T.hdf5
    python `which imglss-query-completeness.py` $OPTIONS --use-tycho-veto=BOSS_DR9 $T $T.hdf5 $T-RANDOM.hdf5
    python `which imglss-export-text.py` $OPTIONS --use-tycho-veto=BOSS_DR9 --bands g r z W1 W2 -- $T $T.hdf5 $T.txt
    python `which imglss-export-text.py` $OPTIONS --use-tycho-veto=BOSS_DR9 --bands g r z W1 W2 -- $T $T-RANDOM.hdf5 $T-RANDOM.txt
    ) &
done

wait
