#!/bin/bash

# This head node script will post process all target types given on the command line
# in parallel, on a head node.
 
# Require: RANDOM.hdf5 generated by make_rans.job
# Require: {TARGET}.hdf5 generated by select_objs.job

# http://stackoverflow.com/a/8366378

# kill sub-shells if the script is killed.

trap "kill 0" SIGINT

OPTIONS="--conf /project/projectdirs/m779/yfeng1/imaginglss/dr2.conf.py "
OPTIONS+="--extra-target-definitions targets "

if ! [ -f RANDOM.hdf5 ]; then
    echo "RANDOM.hdf5 not found!"
    exit 1
fi

for T in $*; do
    cp RANDOM.hdf5 $T-RANDOM.hdf5
    (
    set -x
    python ../scripts/imglss-query-tycho-veto.py $OPTIONS $T-RANDOM.hdf5
    python ../scripts/imglss-query-tycho-veto.py $OPTIONS $T.hdf5
    python ../scripts/imglss-query-completeness.py $OPTIONS --use-tycho-veto=BOSS_DR9 $T $T.hdf5 $T.hdf5
    python ../scripts/imglss-query-completeness.py $OPTIONS --use-tycho-veto=BOSS_DR9 $T $T.hdf5 $T-RANDOM.hdf5
    python '../scripts/imglss-export-text.py' $OPTIONS --use-tycho-veto=BOSS_DR9 --bands r g z W1 W2 -- $T $T.hdf5 $T.txt
    python '../scripts/imglss-export-text.py' $OPTIONS --use-tycho-veto=BOSS_DR9 --bands r g z W1 W2 -- $T $T-RANDOM.hdf5 $T-RANDOM.txt
    ) &
done

wait
