#!/bin/bash

#SBATCH -A desi
#SBATCH -J select_objs
#SBATCH -n 32
#SBATCH -o select_objs.%j
#SBATCH -p debug
#SBATCH -t 00:20:00

export OMP_NUM_THREADS=1
set -x

source /usr/common/contrib/bccp/conda-activate.sh 3.6

(cd ../; python setup.py sdist )
version=`python ../setup.py --version`

bcast-pip ../dist/imaginglss-$version.tar.gz

# http://www.nersc.gov/users/data-analytics/data-management/i-o-libraries/hdf5-2/h5py/#toc-anchor-6
export HDF5_USE_FILE_LOCKING=FALSE  


OPTIONS=" --conf /project/projectdirs/m779/yfeng1/imaginglss/dr5.conf.py "
#OPTIONS+=" --extra-target-definitions targets "

for T in ELG LRG QSO; do
    time srun -n 16 python ../scripts/imglss-mpi-select-objects.py \
    $OPTIONS \
    ${T} \
    /project/projectdirs/desi/users/yfeng1/imaginglss/legacysurvey/dr5/${T}.hdf5
done

