#!/bin/bash

#SBATCH -A desi
#SBATCH -J select_objs
#SBATCH -n 32
#SBATCH -o select_objs.%j
#SBATCH -p debug
#SBATCH -t 00:20:00

export OMP_NUM_THREADS=1
set -x

module load python/3.5-anaconda
source /usr/common/contrib/bccp/python-mpi-bcast/nersc/activate.sh

# install the 'nersc' version of imaginglss
bcast-pip bigfile /project/projectdirs/desi/users/yfeng1/imaginglss/imaginglss

OPTIONS=" --conf /project/projectdirs/desi/users/yfeng1/imaginglss/legacysurvey/dr3.conf.py "
OPTIONS+=" --extra-target-definitions targets "

for T in ELG LRG QSO; do
    time srun -n 16 python-mpi /dev/shm/local/bin/imglss-mpi-select-objects.py \
    $OPTIONS \
    ${T} \
    /project/projectdirs/desi/users/yfeng1/imaginglss/legacysurvey/dr3/${T}.hdf5
done

