#!/bin/bash

#SBATCH -A desi
#SBATCH -J select_objs
#SBATCH -n 512
#SBATCH -o select_objs.%j
#SBATCH -p debug
#SBATCH -t 00:14:00

export OMP_NUM_THREADS=1
set -x

module load python/2.7-anaconda
source /project/projectdirs/m779/python-mpi/nersc/activate.sh

mirror ../ imaginglss scripts

# use without installing
export PYTHONPATH=/dev/shm/local:$PYTHONPATH

time srun -n 256 python-mpi /dev/shm/local/scripts/imglss-mpi-select-objects.py LRG LRG.hdf5 --conf /project/projectdirs/m779/yfeng1/imaginglss/dr2.conf.py

time srun -n 256 python-mpi /dev/shm/local/scripts/imglss-mpi-make-random.py 10000000 LRG-RANDOM.hdf5 --conf /project/projectdirs/m779/yfeng1/imaginglss/dr2.conf.py

#srun -n 256 python-mpi /dev/shm/local/scripts/select_objs.py QSO QSO.txt --with-tycho DECAM_QSO --conf /project/projectdirs/m779/imaginglss/dr2.conf.py
