#!/bin/bash

#SBATCH -J select_objs
#SBATCH -n 512
#SBATCH -o select_objs.%j
#SBATCH -p debug
#SBATCH -t 00:14:00

export OMP_NUM_THREADS=1

module load python/2.7-anaconda

source /project/projectdirs/m779/python-mpi/nersc/activate.sh

mirror ../ imaginglss scripts

# use without installing
export PYTHONPATH=/dev/shm/local:$PYTHONPATH

srun -n 256 python-mpi /dev/shm/local/scripts/imglss-mpi-select-objects.py LRG LRG.hdf5 --conf /project/projectdirs/m779/imaginglss/dr2.conf.py