from imaginglss.model.catalogue import C
from imaginglss.utils.npyquery import Min, Max

RA = C('RA')
DEC = C('DEC')

DECAM_MW_TRANSMISSION = C('DECAM_MW_TRANSMISSION')
DECAM_FLUX = C('DECAM_FLUX')
DECAM_MW_TRANSMISSION = C('DECAM_MW_TRANSMISSION')
WISE_FLUX = C('WISE_FLUX')
WISE_FLUX_IVAR = C('WISE_FLUX_IVAR')
WISE_MW_TRANSMISSION = C('WISE_MW_TRANSMISSION')
BRICK_PRIMARY = C('BRICK_PRIMARY')
TYPE = C('TYPE')

DECAM_PSFSIZE = C('DECAM_PSFSIZE')
DECAM_ANYMASK = C('DECAM_ANYMASK')

SHAPEDEV_R = C('SHAPEDEV_R')
SHAPEEXP_R = C('SHAPEEXP_R')

GFLUX = DECAM_FLUX[1] / DECAM_MW_TRANSMISSION[1]
RFLUX = DECAM_FLUX[2] / DECAM_MW_TRANSMISSION[2]
ZFLUX = DECAM_FLUX[4] / DECAM_MW_TRANSMISSION[4]
W1FLUX = WISE_FLUX[0] / WISE_MW_TRANSMISSION[0]
W2FLUX = WISE_FLUX[1] / WISE_MW_TRANSMISSION[1]
WFLUX = 0.75 * WISE_FLUX[0] / WISE_MW_TRANSMISSION[0] \
      + 0.25 * WISE_FLUX[1] / WISE_MW_TRANSMISSION[1]
GRZFLUX = (GFLUX + 0.8* RFLUX + 0.5* ZFLUX ) / 2.4
SNRW1 = (WISE_FLUX[0] * WISE_FLUX_IVAR[0] ** 0.5)
SNRW2 = (WISE_FLUX[1] * WISE_FLUX_IVAR[1] ** 0.5)
